// Generated by Selenium IDEconst { Builder, By, Key, until, webdriver } = require('selenium-webdriver')
const { Builder, By, Key, until, webdriver } = require('selenium-webdriver')
var chrome = require ('selenium-webdriver/chrome');
require('chromedriver')
describe('testconnexion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = new Builder().forBrowser('chrome').setChromeOptions((new chrome.Options).addArguments('--headless').addArguments('--no-sandbox').addArguments('--disable-dev-shm-usage')).build()
    vars = {}
  })
  afterEach(async function() {
    
  })
  it('testconnexion', async function() {
    // Test name: testconnexion
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://jobaas-backend-dev.herokuapp.com//")
    // 2 | setWindowSize | 1366x658 | 
    await driver.manage().window().setRect({ width: 1366, height: 658 })
    // 3 | click | linkText=Se connecter | 
    await driver.findElement(By.linkText("Se connecter")).click()
    // 4 | type | id=email | elangal@3il.fr
    await driver.sleep(7000)
    await driver.findElement(By.id("email")).sendKeys("elangal@3il.fr")
    // 5 | type | id=password | string9S#
    await driver.findElement(By.id("password")).sendKeys("string9S#")
    // 6 | click | id=state | 
    await driver.findElement(By.id("state")).click()
    // 7 | click | css=.ant-select-item-option-active > .ant-select-item-option-content | 
    await driver.findElement(By.css(".ant-select-item-option-active > .ant-select-item-option-content")).click()
    // 8 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 9 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 10 | click | css=.Login_content__DXecL | 
    await driver.findElement(By.css(".Login_content__DXecL")).click()
    // 11 | click | css=.ant-btn-primary | 
    await driver.findElement(By.css(".ant-btn-primary")).click()
  })
})
