// Generated by Selenium IDE
const { Builder, By, Key, until, webdriver } = require('selenium-webdriver')
var chrome = require ('selenium-webdriver/chrome');
require('chromedriver')


describe('testconnexion_employeur', function() {
  this.timeout(300000)
  let driver
  let vars
  beforeEach(async function() {
    
    driver = new Builder().forBrowser('chrome').setChromeOptions((new chrome.Options).addArguments('--headless').addArguments('--no-sandbox').addArguments('--disable-dev-shm-usage')).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testconnexion_employeur', async function() {
    // Test name: testconnexion_employeur
    // Step # | name | target | value
    // 1 | open | https://jobaas-backend-dev.herokuapp.com/ | 
    await driver.get("https://jobaas-backend-dev.herokuapp.com/")
    // 2 | setWindowSize | 857x560 | 
    await driver.manage().window().setRect({ width: 857, height: 560 })
    // 3 | click | linkText=Se connecter | #root > header > div > div.Header_container__251eY.grid-12-small-4 > ul > li.login
    await driver.findElement(By.linkText('Se connecter')).click()
    // 4 | type | id=email | leonel@yahoo.fr
    await driver.sleep(7000)
    await driver.findElement(By.id('email')).sendKeys("leonel@yahoo.fr") 
    // 5 | type | id=password | string9S#
    await driver.findElement(By.id("password")).sendKeys("string9S#")
    // 6 | click | id=state | 
    await driver.findElement(By.id("state")).click()
    // 7 | click | css=.ant-select-item-option-active > .ant-select-item-option-content | 
    await driver.findElement(By.css(".ant-select-item-option-active > .ant-select-item-option-content")).click()
    // 8 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 9 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 10 | click | css=.ant-btn > span | 
    await driver.findElement(By.css(".ant-btn > span")).click()
  })
})
