/** *******
 * production.js
 *********/

const envConfig = {
    hostname: 'jobaas.cm',
    port: process.env.PORT,
    databaseUri: process.env.DATABASE_URI,
    databaseName: process.env.DATABASE_NAME,
    populateDatabase: false,
    jwt_secret: process.env.JWT_SECRET,
    IP_ADMIN: process.env.IP_ADMIN,
    job_price_min: process.env.JOB_PRICE_MIN,
    payment_type_fees: process.env.PAYMENT_TYPE_FEES,
    API_KEY_GOOGLE_MAP: process.env.API_KEY_GOOGLE_MAP,
    jwt_expiration_in_seconds: process.env.EXPIRE_TIME,
    rate_limit_in_milliseconds: process.env.RATELIMITER_TIME,
    rate_block_limit_seconds: process.env.RATEBLOCKLIMITER_TIME,
    sr: process.env.SR,
    no_mail: process.env.NO_MAIL || 0,
    no_sms: process.env.NO_SMS || 1,
    it_mails:process.env.IT_MAILS.split(","),
    cto_mail: process.env.CTO_MAIL,
    marketing_mails: process.env.MARKETING_MAILS.split(","),
    twilio_account_sid: process.env.TWILIO_ACCOUNT_SID ,
    twilio_auth_token: process.env.TWILIO_AUTH_TOKEN  ,
    twilio_virtual_number:"+17243902719", 
    redis_url: process.env.REDIS_URL,
    permissionLevels: {
        'EMPLOYER_USER': 5,
        'EMPLOYEE_USER': 7,
        'ENTREPRISE_USER': 10,
        'ADMIN': 2048,
        'CONTROLLER_USER': 777,
        'SUP_ADMIN': 1468,
        'RH_USER': 888,
        'COMMERCIAL_USER': 666,
        'COMMUNICATION_USER': 666
    },
    mailgun_apikey: process.env.MAILGUN_API_KEY,
    mailgun_domain: process.env.MAILGUN_DOMAIN,
    mailgun_host: process.env.MAILGUN_HOST,
    user_api_sms: process.env.USER_API_SMS,
    password_api_sms: process.env.PASSWORD_API_SMS,
    phonenumbers: 690637982,
    logsene_token: process.env.LOGSENE_TOKEN,
    exception_transaction_process: process.env.EXCEPTION_TRANSACTION || Number('0'),
    bucketName: process.env.bucketName,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_REGION: process.env.AWS_REGION,
    modeTest: process.env.MODE_TEST || 0,
    forestAuthSecret: process.env.FOREST_AUTH_SECRET,
    forestEnvSecret: process.env.FOREST_ENV_SECRET,
    prerender: process.env.PRERENDER,
};

module.exports = envConfig;
