// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
var chrome = require ('selenium-webdriver/chrome');
require('chromedriver')

describe('candidatures_&_employés', function() {
  this.timeout(300000)
  let driver
  let vars
  beforeEach(async function() {
    driver = new Builder().forBrowser('chrome').setChromeOptions((new chrome.Options).addArguments('--headless').addArguments('--no-sandbox').addArguments('--disable-dev-shm-usage')).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function testconnexionemployeur() {
    await driver.get("https://jobaas-backend-dev.herokuapp.com/")
    await driver.manage().window().setRect({ width: 857, height: 560 })
    await driver.findElement(By.linkText("Se connecter")).click()
    await driver.sleep(17000)
    await driver.findElement(By.id("email")).sendKeys("leonel@yahoo.fr")
    await driver.findElement(By.id("password")).sendKeys("string9S#")
    await driver.findElement(By.id("state")).click()
    await driver.findElement(By.css(".ant-select-item-option-active > .ant-select-item-option-content")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.css(".ant-btn > span")).click()
  }
  it('candidatures_&_employés', async function() {
    // Test name: candidatures_&_employés
    // Step # | name | target | value
    // 1 | run | testconnexion_employeur | 
    testconnexionemployeur()
    // 2 | setWindowSize | 857x560 | 
    await driver.manage().window().setRect({ width: 1366, height: 658 })
    // 3 | click | linkText=Menu Employeur | 
    await driver.sleep(17000)
    await driver.get(driver.getCurrentUrl())
    await driver.sleep(17000)
    await driver.findElement(By.linkText("Menu Employeur")).click()
    // 4 | click | linkText=Mes emplois | 
    await driver.sleep(10000)
    await driver.findElement(By.linkText("Mes emplois")).click()
    // 5 | runScript | window.scrollTo(0,448) | 
    await driver.sleep(10000)
    await driver.executeScript("window.scrollTo(0,448)")
    // 6 | click | css=.col-4:nth-child(4) .ButtonRounded_ButtonDarkBlue__2R9l6 | 
    await driver.sleep(10000)
    await driver.findElement(By.css(".col-4:nth-child(4) .ButtonRounded_ButtonDarkBlue__2R9l6")).click()
    // 7 | runScript | window.scrollTo(0,0) | 
    await driver.sleep(10000)
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
